Add java.util.Function wrapper
ylegat/uncheck pull request #3
Opened 2016-09-16 12:28 UTC by moreau-nicolas

The idea behind this PR is to allow someone to write something akin to:

```java
Stream.of("a", "b", "c")
    .map(uncheck(this::someMethodThatThrowsSomeCheckedException))
    .forEach(System.out::println) // Or something more meaningful...
```

2016-09-28 10:00 UTC, moreau-nicolas commented
Same idea can be applied to BiFunction, Predicate, BiPredicate, Consumer...

2017-06-28 16:21 UTC, ylegat requested changes
Hey! Thanks for the contribution (and sorry for the delay !)
I think we can reduce some logic duplication, but it's a nice improvement anyway ;)

2017-06-28 16:21 UTC, ylegat commented on src/main/java/com/github/ylegat/uncheck/Uncheck.java
> +                return transformer.apply(value);
I think we can reuse the logic of `uncheck(CheckedSupplier<T> supplier)` by just doing this:
```java
    public static <T, R> Function<T, R> uncheck(CheckedFunction<T, R> transformer) {
        return value -> uncheck(() -> transformer.apply(value));
    }
```

2017-06-30 15:07 UTC, moreau-nicolas commented on src/main/java/com/github/ylegat/uncheck/Uncheck.java
> +                return transformer.apply(value);
Yes ! It's done. :)

2017-08-11 13:19 UTC, ylegat approved these changes

2017-08-11 13:20 UTC, merged